/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PageOne {
    }
}
export interface PageOneCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPageOneElement;
}
declare global {
    interface HTMLPageOneElement extends Components.PageOne, HTMLStencilElement {
    }
    var HTMLPageOneElement: {
        prototype: HTMLPageOneElement;
        new (): HTMLPageOneElement;
    };
    interface HTMLElementTagNameMap {
        "page-one": HTMLPageOneElement;
    }
}
declare namespace LocalJSX {
    interface PageOne {
        "onCalciteModalClose"?: (event: PageOneCustomEvent<void>) => void;
        "onNextClick"?: (event: PageOneCustomEvent<{ key: string }>) => void;
    }
    interface IntrinsicElements {
        "page-one": PageOne;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "page-one": LocalJSX.PageOne & JSXBase.HTMLAttributes<HTMLPageOneElement>;
        }
    }
}
